version: '3.8'

services:
  nginx-reverse-proxy:
    env_file:
      - project.env
    image: tuiteraz/nginx-more:1.25.2
    restart: unless-stopped
    container_name: nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-config:/etc/nginx
      - /etc/localtime:/etc/localtime:ro
      - ./letsencrypt:/etc/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  letsenrypt: